<?php
/**
 * Copyright © 2020 CyberSource. All rights reserved.
 * See accompanying LICENSE.txt for applicable terms of use and license.
 */

/** @var $block \CyberSource\WeChatPay\Block\Order\Info\Qr */
?>

<div id="weChatPayQr" style="display: none;" data-bind="mageInit: {
        'CyberSource_WeChatPay/js/view/payment/popup': {
            checkStatusFrequency: <?= $block->getCheckStatusFrequency() ?>,
            maxStatusRequests: <?= $block->getMaxStatusRequests() ?>,
            popupMessageDelay: <?= $block->getPopupMessageDelay() ?>,
            orderId: <?= $block->getOrder()->getEntityId() ?>
        }}">
    <div class="wechatpayqr-wrapper">
        <div class="qr-wrapper"></div>
        <div class="qr-notice"></div>
    </div>
</div>
