<?php

/* @var $block \CyberSource\SecureAcceptance\Block\Flex */

?>
<script type="text/javascript">

    require.config({
        paths: {
            "flex-microform": '<?php echo $block->isSandbox()
                ? 'https://testflex.cybersource.com/cybersource/assets/microform/0.11/flex-microform.min'
                : 'https://flex.cybersource.com/cybersource/assets/microform/0.11/flex-microform.min'; ?>'
        },
        shim: {
            "flex-microform": {
                exports: 'Flex'
            }
        }
    });

</script>

