<?php

namespace CyberSource\Recaptcha\Model\Config\Source;

class Language implements \Magento\Framework\Option\ArrayInterface
{

    public function toOptionArray()
    {
        return [
            ['label' => 'Auto', 'value' => ''],
            ['label' => 'Arabic', 'value' => 'ar'],
            ['label' => 'Afrikaans', 'value' => 'af'],
            ['label' => 'Amharic', 'value' => 'am'],
            ['label' => 'Armenian', 'value' => 'hy'],
            ['label' => 'Azerbaijani', 'value' => 'az'],
            ['label' => 'Basque', 'value' => 'eu'],
            ['label' => 'Bengali', 'value' => 'bn'],
            ['label' => 'Bulgarian', 'value' => 'bg'],
            ['label' => 'Catalan', 'value' => 'ca'],
            ['label' => 'Chinese (Hong Kong)', 'value' => 'zh-HK'],
            ['label' => 'Chinese (Simplified)', 'value' => 'zh-CN'],
            ['label' => 'Chinese (Traditional)', 'value' => 'zh-TW'],
            ['label' => 'Croatian', 'value' => 'hr'],
            ['label' => 'Czech', 'value' => 'cs'],
            ['label' => 'Danish', 'value' => 'da'],
            ['label' => 'Dutch', 'value' => 'nl'],
            ['label' => 'English (UK)	', 'value' => 'en-GB'],
            ['label' => 'English (US)', 'value' => 'en'],
            ['label' => 'Estonian', 'value' => 'et'],
            ['label' => 'Filipino	', 'value' => 'fil'],
            ['label' => 'Finnish', 'value' => 'fi'],
            ['label' => 'French', 'value' => 'fr'],
            ['label' => 'French (Canadian)	fr', 'value' => 'CA'],
            ['label' => 'Galician', 'value' => 'gl'],
            ['label' => 'Georgian', 'value' => 'ka'],
            ['label' => 'German', 'value' => 'de'],
            ['label' => 'German (Austria)', 'value' => 'de-AT'],
            ['label' => 'German (Switzerland)', 'value' => 'de-CH'],
            ['label' => 'Greek', 'value' => 'el'],
            ['label' => 'Gujarati', 'value' => 'gu'],
            ['label' => 'Hebrew', 'value' => 'iw'],
            ['label' => 'Hindi', 'value' => 'hi'],
            ['label' => 'Hungarain', 'value' => 'hu'],
            ['label' => 'Icelandic', 'value' => 'is'],
            ['label' => 'Indonesian', 'value' => 'id'],
            ['label' => 'Italian', 'value' => 'it'],
            ['label' => 'Japanese', 'value' => 'ja'],
            ['label' => 'Kannada', 'value' => 'kn'],
            ['label' => 'Korean', 'value' => 'ko'],
            ['label' => 'Laothian', 'value' => 'lo'],
            ['label' => 'Latvian', 'value' => 'lv'],
            ['label' => 'Lithuanian', 'value' => 'lt'],
            ['label' => 'Malay', 'value' => 'ms'],
            ['label' => 'Malayalam', 'value' => 'ml'],
            ['label' => 'Marathi', 'value' => 'mr'],
            ['label' => 'Mongolian', 'value' => 'mn'],
            ['label' => 'Norwegian', 'value' => 'no'],
            ['label' => 'Persian', 'value' => 'fa'],
            ['label' => 'Polish', 'value' => 'pl'],
            ['label' => 'Portuguese', 'value' => 'pt'],
            ['label' => 'Portuguese (Brazil)', 'value' => 'pt-BR'],
            ['label' => 'Portuguese (Portugal)', 'value' => 'pt-PT'],
            ['label' => 'Romanian', 'value' => 'ro'],
            ['label' => 'Russian', 'value' => 'ru'],
            ['label' => 'Serbian', 'value' => 'sr'],
            ['label' => 'Sinhalese', 'value' => 'si'],
            ['label' => 'Slovak', 'value' => 'sk'],
            ['label' => 'Slovenian', 'value' => 'sl'],
            ['label' => 'Spanish', 'value' => 'es'],
            ['label' => 'Spanish (Latin America)', 'value' => 'es-419'],
            ['label' => 'Swahili', 'value' => 'sw'],
            ['label' => 'Swedish', 'value' => 'sv'],
            ['label' => 'Tamil', 'value' => 'ta'],
            ['label' => 'Telugu', 'value' => 'te'],
            ['label' => 'Thai', 'value' => 'th'],
            ['label' => 'Turkish', 'value' => 'tr'],
            ['label' => 'Ukrainian', 'value' => 'uk'],
            ['label' => 'Urdu', 'value' => 'ur'],
            ['label' => 'Vietnamese', 'value' => 'vi'],
            ['label' => 'Zulu', 'value' => 'zu'],
        ];
    }
}
