<?php if ($this->isFingerprintEnabled()) : ?>
    <?php if ($block->getOrgId() !== null) : ?>
        <script type="text/javascript" src="<?php echo $block->getJsUrl(); ?>"></script>
    <?php endif; ?>
    <noscript>
        <iframe style="width: 100px; height: 100px; border: 0; position: absolute; top: -5000px;" src="<?php echo $block->getIframeUrl(); ?>"></iframe>
    </noscript>
<?php endif; ?>