<?php /* @var $block \CyberSource\Core\Block\Adminhtml\System\Config\DecisionManagerOnDemand */ ?>

<div class="field">
    <input type="text" class="input-text" id="dm_update_date" style="width: 80%" name="dm_update_date" />
</div>

<?= $block->getButtonHtml() ?>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'Magento_Ui/js/modal/confirm',
        'mage/translate',
        'mage/calendar'
    ], function($, alert, confirm, $t) {

        function startUpdate() {

            $.post('<?= $block->getUpdateUrl() ?>',
                {
                    date: $('#dm_update_date').val(),
                    form_key: FORM_KEY
                }
            ).done(function (response) {
                    if (response.status) {
                        alert({
                            content: 'Complete! Check the var/log/cybs.log file for Report Details.'
                        });
                    } else {
                        alert({
                            content: response.error
                        });
                    }
                    $('#config-edit-form').trigger('processStop');
                }
            );

        }



        $('#dm_update_date').calendar({
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            currentText: $t('Go Today'),
            closeText: $t('Close'),
            dateFormat: 'yyyy-MM-dd',
            timeFormat: 'HH:mm:ss',

            showsTime: true
        });

        $('#dm_update_button').click(function() {

            var startDate = $('#dm_update_date').val();
            console.log(startDate);
            if (startDate) {
                confirm({
                    content: 'Are you sure you want to perform manual update?',
                    actions: {
                        confirm: function () {
                            $('#config-edit-form').trigger('processStart');
                            startUpdate();
                        }
                    }
                });
            }
            else {
                alert({
                    title: $.mage.__('Data Input Error'),
                    content: $.mage.__('Please select a valid date in the past to initiate the DM Job Update.'),
                    actions: {
                        always: function(){}
                    }
                });
            }
        });
    });
</script>
